name: HaNPlugin
main: mangobox.main.HaNMain
version: 0.1
commands:
   setmaxhealth:
     description: Sets your max health!
     usage: /<command>
   setspeed:
     description: Sets your walking speed!
     usage: /<command>  
   getitemmat:
     description: Gets the material name in your hand.
     usage: /<command>
   health:
     description: Shows the health of your character.
     usage: /<command>
   sethunger:
     description: Sets the players hunger
     usage: /<command>